#!/bin/bash

DEBUG=0
cmd=""

case "$1" in
help )
  source ${BASH_SOURCE%/*}/help/help.sh "nancy"
  exit 1;
  ;;
* )
  word="${1/-/_}"
  if [[ ! -f "${BASH_SOURCE%/*}/nancy_$word.sh" ]]; then
    >&2 echo "ERROR: Unknown command: $word."
    >&2 echo "Try 'nancy help'"
    exit 1
  fi
  cmd="${BASH_SOURCE%/*}/nancy_$word.sh"
  shift;
  ;;
esac

while [ -n "$1" ]; do
  if [ "$1" == "--debug" ]; then
    DEBUG=1
  fi
  if [ ${1%"${1#??}"} = '--' ]; then
    cmd="$cmd $1"
  else
    cmd="$cmd \"$1\""
  fi
  shift
done

[[ "$DEBUG" -eq "1" ]] && echo "CMD: $cmd"

eval "$cmd"
