#!/bin/bash

DEBUG=0
cmd=""

case "$1" in
    help )
        echo -e "
\033[1mDESCRIPTION\033[22m

  The Nancy Command Line Interface is a unified way to manage database
  experiments.

  Nancy is a member of Postgres.ai's Artificial DBA team responsible for
  conducting experiments.

\033[1mSYNOPSYS\033[22m

  nancy <command> [parameters]

\033[1mAVAILABLE COMMANDS\033[22m

  * help

  * prepare-database (WIP)

  * prepare-workload

  * run
  " | less -RFX
  exit 1;
  ;;
* )
  word="${1/-/_}"
  if [[ ! -f "${BASH_SOURCE%/*}/nancy_$word.sh" ]]; then
    >&2 echo "ERROR: Unknown command: $word."
    >&2 echo "Try 'nancy help'"
    exit 1
  fi
  cmd="${BASH_SOURCE%/*}/nancy_$word.sh"
  shift;
  ;;
esac

while [ -n "$1" ]; do
  if [ "$1" == "--debug" ]; then
    DEBUG=1
  fi
  if [ ${1%"${1#??}"} = '--' ]; then
    cmd="$cmd $1"
  else
    cmd="$cmd \"$1\""
  fi
  shift
done

[[ "$DEBUG" -eq "1" ]] && echo "CMD: $cmd"

eval "$cmd"
